### ISSUE TITLE
Does not work on gnome-shell 3.35.2

### ISSUE THREAD

**Issue by flyingpimonster** [mlutfy/hidetopbar#199]
On gnome-shell 3.35.2, the extension is not loaded. In Looking Glass, the error is `TypeError: PanelBox.get_anchor_point is not a function`

This is on Fedora Rawhide. The extension is installed from the Software app.
